### ISSUE TITLE
Not working with ZSH and oh my zsh

### ISSUE THREAD

**Issue by 57r4n63r** [promptops/cli#2]
Pretty self explanatory.
It looks like it's not working with ZSH and oh my zsh installed.
Something about utf-8 codec
![Selection_259](https://github.com/promptops/cli/assets/34603831/93027573-47da-4bbf-a9a4-b5c7ae9f6e86)

**Comment by jj-ctrlstack** [comment]
@57r4n63r I think I found the issue, do you mind upgrading and giving it a try.

```
pip3 install -U git+https://github.com/promptops/cli.git
```

**Comment by jj-ctrlstack** [comment]
@gilzow -- if you are willing to try with pip3 using latest, the command I just posted? We can then update the brew version as well.

**Comment by 57r4n63r** [comment]
Looks like the problem is still there.

**Comment by gilzow** [comment]
just tried. gives an even bigger stack trace:
<img width="977" alt="image" src="https://github.com/promptops/cli/assets/2332956/5284eecf-63cf-4eb9-bcbf-3310c943080d">

**Comment by jj-ctrlstack** [comment]
Yikes, can you provide more info of your system - what's your OS + shell that you are using. I wonder if this can be utf-16 encoded.

**Comment by gilzow** [comment]
macOS 11.7.4
```
❯ zsh --version
zsh 5.8 (x86_64-apple-darwin20.0)
```

**Comment by 57r4n63r** [comment]
I'm using Pop!_OS 22.04 LTS,
Gnome terminal.
zsh 5.8.1 (x86_64-ubuntu-linux-gnu)
"Oh my zsh" almost vanilla config
![Selection_260](https://github.com/promptops/cli/assets/34603831/27c854b8-5f34-4b5b-9d99-bf72aa7b8c77)

**Comment by gilzow** [comment]
I uninstalled and reinstalled. While it no longer throws an error, it also just hangs. It's been sitting for greater than 5 minutes not doing anything after requesting a command (same as before: `um list branches in git`)

```
❯ um --version
0.1.4
```

**Comment by jj-ctrlstack** [comment]
Thanks for your patience with this. I think what might be happening is that now it's attempting to index the history but outside the configuration flow we were not showing progress bar. Pushed a fix for this, but you can also run `um --config` to re-configure.

**Comment by 57r4n63r** [comment]
Seems like it's working fine now. thanks !

**Comment by gilzow** [comment]
yep, version 0.1.5 is working for me now as well. Thanks!
