### ISSUE TITLE
`brew upgrade` won't pull in new changes with a sha-only update

### ISSUE THREAD

**Issue by wgordon17** [promptops/cli#3]
Given the issue and fix to support `fish` (https://www.reddit.com/r/devops/comments/13q48o5/comment/jldymhz/?utm_source=share&utm_medium=web2x&context=3), I was instructed to just `brew upgrade promptops/promptops/promptops-cli`. Unfortunately, that didn't work

```
$ brew upgrade promptops/promptops/promptops-cli

Warning: promptops/promptops/promptops-cli 0.1.2 already installed
```

because the only thing that changed was the sha: https://github.com/promptops/homebrew-promptops/commit/f3bb94ae423a8e58c588d6e81b641d18746915d8

**Comment by jj-ctrlstack** [comment]
@wgordon17 Thanks for reporting this! We'll definitely get better with release versions, but just as a quick workaround do you mind trying to uninstall and then brew install?

**Comment by wgordon17** [comment]
@jj-ctrlstack My apologies, I performed said `uninstall`/`install` dance already, and was able to successfully upgrade the CLI. I was just reporting this mostly as an FYI 😉

**Comment by jj-ctrlstack** [comment]
Got it! Appreciate you reporting the issue and we'll definitely resolve, I wasn't aware brew behaves this way. I'll keep this open until we resolve in case someone else runs into this. Thank you!
